name: 'Run unit tests'
on:
  push:
    branch:
      - master
  pull_request:
    branch:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ubuntu noble apt-repos
        run: |
          sed -i 's/jammy/noble/g' /etc/apt/sources.list
      - name: Install deps
        run: |
          apt-get -y update && \
          apt-get -y install libgtk-4-dev valac meson \
          ninja-build libgee-0.8-dev libadwaita-1-dev \
          gettext desktop-file-utils appstream libxml2-utils
      - name: Setup project
        run: meson setup builddir
      - name: Compile project
        run: meson compile -C builddir
      - name: Run Unit Tests
        run: meson test -C builddir
          