name: 'Run unit tests'
on:
  push:
    branch:
      - master
  pull_request:
    branch:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ubuntu noble apt-repos
        run: | 
          sudo sed -i 's/jammy/noble/g' /etc/apt/sources.list
          sudo apt-get -y update
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            libgtk-4-dev valac meson ninja-build \
            libgee-0.8-dev libadwaita-1-dev gettext \
            desktop-file-utils appstream libxml2-utils
          version: ${{ runner.os }}-${{ hashFiles('./meson.build') }}
      - name: Setup project
        run: meson setup builddir
      - name: Compile project
        run: meson compile -C builddir
      - name: Run Unit Tests
        run: meson test -C builddir
